### ISSUE TITLE
Error after Installation of RP2040-FreeRTOS

### ISSUE THREAD

**Issue by benji7480** [smittytone/RP2040-FreeRTOS#10]
Thanks for this FreeRTOS bundle on the Pi Pico. I am trying to run it on the VS IDE and have 1 error in the build so far as below - copied from the o/p terminal:

[main] Building folder: RP2040-FreeRTOS-main 
[main] Configuring project: RP2040-FreeRTOS-main 
[proc] Executing command: "C:\Program Files\Raspberry Pi\Pico SDK v1.5.1\cmake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files\Raspberry Pi\Pico SDK v1.5.1\gcc-arm-none-eabi\bin\arm-none-eabi-gcc.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files\Raspberry Pi\Pico SDK v1.5.1\gcc-arm-none-eabi\bin\arm-none-eabi-g++.exe" -SC:/Users/bvu3kor/Documents/Pico-v1.5.1/RP2040-FreeRTOS-main -Bc:/Users/bvu3kor/Documents/Pico-v1.5.1/RP2040-FreeRTOS-main/build -G "NMake Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] PICO_SDK_PATH is C:/Users/bvu3kor/Documents/Pico-v1.5.1/pico-sdk
[cmake] PICO platform is rp2040.
[cmake] CMake Error at CMakeLists.txt:56 (project):
[cmake]   Running
[cmake] 
[cmake]    'nmake' '-?'
[cmake] 
[cmake]   failed with:
[cmake] 
[cmake]    The system cannot find the file specified
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/Users/bvu3kor/Documents/Pico-v1.5.1/RP2040-FreeRTOS-main/build/CMakeFiles/CMakeOutput.log".
[proc] The command: "C:\Program Files\Raspberry Pi\Pico SDK v1.5.1\cmake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files\Raspberry Pi\Pico SDK v1.5.1\gcc-arm-none-eabi\bin\arm-none-eabi-gcc.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files\Raspberry Pi\Pico SDK v1.5.1\gcc-arm-none-eabi\bin\arm-none-eabi-g++.exe" -SC:/Users/bvu3kor/Documents/Pico-v1.5.1/RP2040-FreeRTOS-main -Bc:/Users/bvu3kor/Documents/Pico-v1.5.1/RP2040-FreeRTOS-main/build -G "NMake Makefiles" exited with code: 1

From the Problems terminal o/p as below the project() command in the main CMakeLists.txt file fails as below :

CMake Error at CMakeLists.txt:56 (project):Running

 'nmake' '-?'

failed with:

 The system cannot find the file specified

line 56 from the file here for reference
# Name the project
project(${PROJECT_NAME}
        LANGUAGES C CXX ASM
        DESCRIPTION "FreeRTOS-based RP2040 applications"
)

Kindly help to overcome this error. Thanks Benjamin

**Comment by smittytone** [comment]
Difficult to say. The code builds on Linux, but you're using Windows, which I haven't ever used to build the project. Or Visual Studio.

Line 56 of the project-level `CMakeLists.txt` file is actually `${FREERTOS_SRC_DIRECTORY}/event_groups.c`. It's the first FreeRTOS file in the list, which makes me wonder if you haven't installed the repo's FreeRTOS submodule with `git submodule update --init --recursive` called from within the project directory. VS may not have done that for you.

Have you looked at `C:/Users/bvu3kor/Documents/Pico-v1.5.1/RP2040-FreeRTOS-main/build/CMakeFiles/CMakeOutput.log`? Does it give any extra info?

**Comment by smittytone** [comment]
Closed after four months.
