### ISSUE TITLE
App-Timers OOM

### ISSUE THREAD

**Issue by hepoun** [smittytone/RP2040-FreeRTOS#2]
Hi,
it seems App-Timers gets OOM after running slightly over 3 hours ... I left Pico running and when I got back there was no _blinky_ but _shiny_ :-)

```
[DEBUG] Timer fired. ID: 0, LED: on
[DEBUG] Timer fired. ID: 255, LED: off
[DEBUG] Timer fired. ID: 0, LED: on

*** PANIC ***

Out of memory
```
After I changed LED_OFF_TIMER approach from _"create many-times"_ to _"create once, (re)start many-times"_ the problem disappeared. I guess deleting the LED_OFF_TIMER in its callback should resolve the issue too.

**Comment by smittytone** [comment]
I’m impressed you left it running for three hours, but thank you for doing so. I will implement the second fix.

**Comment by smittytone** [comment]
Updated. Ran for five hours w/o panics. Will merge it in.
