### ISSUE TITLE
Multiple core support?

### ISSUE THREAD

**Issue by ObligedTester** [smittytone/RP2040-FreeRTOS#5]
Hello,

Thank you for this perfect demonstration for the RP2040.
I'm pretty new to the freeRTOS side of things and trying to figure out all the different versions available.
I'm having hard time to see if this is the SMP-version of the kernel? 

If so, any further information on how this impact scheduling setup and so on? 

Appreciate any assistance!

**Comment by smittytone** [comment]
It's not the SMP version, no. That wasn't available when this code and the related blog posts were written. I shall have to prepare some updates!
