### ISSUE TITLE
A lot of extraneous submodules cloned

### ISSUE THREAD

**Issue by AXKuhta** [smittytone/RP2040-FreeRTOS#6]
Hello! I just wanted to note that when the repository is cloned as [described in the README](https://github.com/smittytone/RP2040-FreeRTOS#usage) a lot of extraneous code is downloaded as part of tinyusb; final folder size ends up being 3.7 GB:

![Screenshot from 2023-10-18 22-48-46](https://github.com/smittytone/RP2040-FreeRTOS/assets/11133304/30ea3442-77f3-46ac-8ae7-c0089467f875)

To prevent this, submodules need to be updated selectively:

```
git clone https://github.com/smittytone/RP2040-FreeRTOS
cd RP2040-FreeRTOS/
git submodule update --init
cd pico-sdk/
git submodule update --init
cd ..
```

This results in a much more reasonable ~640 MB directory.

Would you mind updating the README with these commands?

**Comment by smittytone** [comment]
I'll take a look.
